[build]
  command = "cd frontend && npm install && npm run build -- --configuration production"
  publish = "frontend/dist/record-store-frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
